apiVersion: v1
kind: Service
metadata:
  name: prod-assistant-service
spec:
  type: LoadBalancer
  selector:
    app: prod-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001  